package com.lumen.launcher.search

import com.lumen.launcher.data.SpaceKind
import com.lumen.launcher.flow.FlowModule

sealed class LauncherCommand {
    data object OpenFlow : LauncherCommand()
    data object OpenHome : LauncherCommand()
    data object OpenDrawer : LauncherCommand()
    data object OpenSearch : LauncherCommand()
    data object OpenRecents : LauncherCommand()
    data object OpenSettings : LauncherCommand()
    data object OpenPersonalize : LauncherCommand()
    data object OpenPrivate : LauncherCommand()
    data class SwitchSpace(val space: SpaceKind?) : LauncherCommand()
    data class IconSize(val sizeDp: Float? = null, val delta: Float? = null) : LauncherCommand()
    data class Labels(val show: Boolean) : LauncherCommand()
    data class Grid(val columns: Int) : LauncherCommand()
    data class DockCapacity(val count: Int) : LauncherCommand()
    data class CreateFolder(val name: String? = null, val apps: List<String> = emptyList()) : LauncherCommand()
    data class AddToFolder(val appName: String, val folderName: String, val extraApps: List<String> = emptyList()) : LauncherCommand()
    data class Pin(val name: String) : LauncherCommand()
    data class Unpin(val name: String) : LauncherCommand()
    data class Dock(val name: String) : LauncherCommand()
    data class Undock(val name: String) : LauncherCommand()
    data class HideApp(val name: String) : LauncherCommand()
    data class UnhideApp(val name: String) : LauncherCommand()
    data class MoveToPrivate(val name: String) : LauncherCommand()
    data class RemoveFromPrivate(val name: String) : LauncherCommand()
    data class WhereApp(val name: String) : LauncherCommand()
    data class LearnAlias(val alias: String, val name: String) : LauncherCommand()
    data object HideNews : LauncherCommand()
    data object ShowNews : LauncherCommand()
    data class SetFlowCard(val module: FlowModule, val enabled: Boolean) : LauncherCommand()
    data class MoveFlowCard(val module: FlowModule, val before: FlowModule?) : LauncherCommand()
    data object NeedNow : LauncherCommand()
    data object UsedYesterday : LauncherCommand()
    data object Weather : LauncherCommand()
    data object NextEvent : LauncherCommand()
    data object InboxDigest : LauncherCommand()
    data object Help : LauncherCommand()
    data object EndTalk : LauncherCommand()
    data class OpenApp(val name: String) : LauncherCommand()
    data class Purpose(val query: String) : LauncherCommand()
}
